%YAML 1.1
---
name: Process Nim
on:
  push:
    branches: [master] # TODO: Only restrict to `master` for docs.
    paths:
    - .github/workflows/**
    - '*.nimble'
    - '**.nim'
    - '**.nims'
    - '**nim.cfg'
    - '**nimdoc.cfg'
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: nim # TODO: ci-${{ github.ref }} | docs
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  nim:
    strategy:
      matrix:
        nim-version: ['1.4.0', '1.4.x', '1.6.0', '1.6.x', '2.0.0', '2.0.x', '2.2.0'] # TODO: stable
    name: Test on ${{ matrix.nim-version }}
    runs-on: ubuntu-latest

    steps:
    - name: Cache Nim toolchain
      id: nim-cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ runner.arch }}-Nim-${{ matrix.nim-version }}
        path: |-
          ~/.choosenim/toolchains/
          ~/.choosenim/current
          ~/.nimble/bin/

    - name: Set up Nim toolchain
      if: steps.nim-cache.outputs.cache-hit != 'true'
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Adjust PATH
      run: echo ~/.nimble/bin >>"$GITHUB_PATH"

    - name: Check out the project
      uses: actions/checkout@v4

    - name: Run tests
      run: >-
        nimble -y --verbose test
        --verbosity=2
        --warning[GcUnsafe]=off
        --hint[GlobalVar]=off
        --hint[Link]=off
        --hint[MsgOrigin]=off

    - name: Generate API docs
      if: matrix.nim-version == '2.2.0'
      run: >-
        nimble doc src/asyncIters.nim
        --git.url="${{ github.server_url }}/${{ github.repository }}"
        --git.commit="${{ github.ref_name }}"

    - name: Set up Pages
      if: matrix.nim-version == '2.2.0'
      uses: actions/configure-pages@v5

    - name: Upload API docs
      if: matrix.nim-version == '2.2.0'
      uses: actions/upload-pages-artifact@v3
      with:
        path: htmldocs/

  deploy-pages:
    name: Deploy Pages
    needs: nim
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Pages
      id: deployment
      uses: actions/deploy-pages@v4
